### ISSUE TITLE
login

### ISSUE THREAD

**Issue by joecrosetto987** [luckyshot/CRMx#6]
Mr. Luckyshot,
Thank you for your amazing app and the amazing detail with which you documented it. I am a somewhat new developer and am having trouble understanding the login process. I have read it over and over but must be missing something. 

I am trying to run this in a WAMP environment.

I see in the config file where I specify a user and password. I know I should create a super long password for production but to keep things simple for a test, I just left the default values in the config file for the user, i.e. name = Tester, password = test. Am I to create a folder under crmx called login/test? I read that I should supply the user with this url and they would bookmark it and go to this bookmark to log in. But what document should be at this location?

I know the problem is that I am very green. Thanks for your time explaining something simple.
Best Regards,
Joe

Am I suppose to creat a director

**Comment by luckyshot** [comment]
Hi @joecrosetto987 

You just need to access the URL `http://example.com/login/test`, CRMx will do the rest and login to the account with the `test` password. No need to create a folder or anything.
