### ISSUE TITLE
still alive and in development?

### ISSUE THREAD

**Issue by petrk94** [luckyshot/CRMx#7]
Hello,

I would like to know whether CRMx is still alive?

**Comment by luckyshot** [comment]
Hi @petrk94 ,
The software works and is finished. You can use it.
New features are on hold although any issues or bugs that arise are worked on.

**Comment by petrk94** [comment]
@luckyshot 
well, really finished it doesnt look like, the mysql must be typed in manually in the config.php and after opening it in the browser, I get "You are not logged in", without any option how to login, maybe make a signup/login page + multiuser support?

**Comment by luckyshot** [comment]
Feel free to edit how you connect to the DB, that's why it's open source.
As per users, I don't think you've read the README... It explains step by step how to create users and login.
